# Generated by Django 3.1.2 on 2020-10-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Christy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('exam_score', models.IntegerField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('exam_score', models.IntegerField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('exam_score', models.IntegerField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('exam_score', models.IntegerField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
