# Generated by Django 3.1.2 on 2020-10-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201029_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emmamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.IntegerField()),
                ('second_test', models.IntegerField()),
                ('total_test', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Christy',
        ),
        migrations.DeleteModel(
            name='Emma',
        ),
        migrations.DeleteModel(
            name='Imo',
        ),
        migrations.DeleteModel(
            name='Rob',
        ),
    ]
