# Generated by Django 3.1.2 on 2020-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201029_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Christymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.IntegerField()),
                ('second_test', models.IntegerField()),
                ('total_test', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.IntegerField()),
                ('second_test', models.IntegerField()),
                ('total_test', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Robmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.IntegerField()),
                ('second_test', models.IntegerField()),
                ('total_test', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
    ]
