# Generated by Django 3.1.2 on 2020-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201029_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christymodel',
            name='comment',
            field=models.CharField(choices=[('p', 'Pass'), ('f', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emmamodel',
            name='comment',
            field=models.CharField(choices=[('p', 'Pass'), ('f', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='imomodel',
            name='comment',
            field=models.CharField(choices=[('p', 'Pass'), ('f', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='robmodel',
            name='comment',
            field=models.CharField(choices=[('p', 'Pass'), ('f', 'Fail')], max_length=10),
        ),
    ]
