# Generated by Django 3.1.2 on 2020-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20201029_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christymodel',
            name='comment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emmamodel',
            name='comment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='imomodel',
            name='comment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
        migrations.AlterField(
            model_name='robmodel',
            name='comment',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
    ]
